class AppStrings {
  static const Map<String, Map<String, String>> translations = {
    'id': {
      'appTitle': 'Perencana Anggaran',
      'language': 'Bahasa',
      'chooseLanguage': 'Pilih Bahasa',
      'budgetList': 'Daftar Budget',
      'statistics': 'Statistik',
      'settings': 'Pengaturan',
      'addExpense': 'Catat Pengeluaran',
      'noExpenseDate': 'Belum ada pengeluaran di tanggal ini.',
      'menu Utama': 'Menu Utama',
      'manageBudget': 'Kelola kategori dan alokasi dana',
      'analytics': 'Analisis grafik pengeluaran',
      'aboutPrefs': 'Tentang aplikasi dan preferensi',
      'generalSettings': 'Pengaturan Umum',
      'selectLanguagePrompt': 'Silakan pilih bahasa yang ingin Anda gunakan.',
      'save': 'Simpan',
      'cancel': 'Batal',
      'close': 'Tutup',
      'expenseName': 'Nama Pengeluaran',
      'expenseNameExample': 'Nama Pengeluaran (Cth: Nasi Goreng)',
      'amount': 'Nominal (Rp)',
      'addBudget': 'Tambah Budget',
      'editBudget': 'Edit Budget',
      'deleteBudget': 'Hapus Budget',
      'deleteConfirm': 'Apakah Anda yakin ingin menghapus budget ini? Semua pengeluaran terkait juga akan dihapus.',
      'deleteExpenseConfirm': 'Apakah Anda yakin ingin menghapus pengeluaran ini?\n\nDana akan dikembalikan ke sisa budget kategori.',
      'totalBalance': 'Total Saldo Bulan Ini',
      'totalExpense': 'Total Pengeluaran Bulan Ini',
      'firstLaunchTitle': 'Selamat Datang!',
      'remainingBudget': 'Sisa Budget',
      'total': 'Total: Rp',
      'spent': 'Terpakai: Rp',
      'expenseHistory': 'Riwayat Pengeluaran',
      'noExpenseCategory': 'Belum ada pengeluaran\ndi kategori ini.',
      'editExpense': 'Edit Pengeluaran',
      'selectBudgetCategory': 'Pilih Kategori Budget',
      'deleteExpenseTitle': 'Hapus Pengeluaran?',
      'delete': 'Hapus',
      'budgetName': 'Nama Budget',
      'allocatedFunds': 'Alokasi Dana (Rp)',
      'noBudgetsYet': 'Belum ada budget.\nSilakan tambah budget baru.',
      'remaining': 'Sisa: Rp',
      'noBudgetAddedYet': 'Belum Ada Budget',
      'addBudgetFirst': 'Silakan tambahkan budget terlebih dahulu sebelum mencatat pengeluaran.',
      'recordExpense': 'Catat Pengeluaran',
      'saveExpense': 'Simpan Pengeluaran',
      'appPreferences': 'Preferensi Aplikasi',
      'darkTheme': 'Tema Gelap',
      'notifications': 'Notifikasi',
      'about': 'Tentang',
      'appVersion': 'Versi Aplikasi',
      'termsConditions': 'Syarat & Ketentuan',
      'privacyPolicy': 'Kebijakan Privasi',
      'expenses': 'Pengeluaran',
      'today': 'Hari Ini',
      'addBudgetNew': 'Tambah Budget Baru',
      'allocatedVsSpent': 'Alokasi vs Terpakai per Kategori',
      'noBudgetData': 'Belum ada data kategori budget.',
      'legend': 'Keterangan',
      'totalBudgetAllocation': 'Total Alokasi Budget',
      'spentSafe': 'Terpakai (Aman)',
      'spentWarning': 'Terpakai (Mendekati / Melebihi Limit)',
      'allExpenses': 'Semua Pengeluaran',
      'totalRemainingBudget': 'Sisa Budget Total',
      'budgetDetails': 'Rincian Budget',
      'noBudgetRecorded': 'Belum ada budget yang dicatat.',
    },
    'en': {
      'appTitle': 'Budget Planner',
      'language': 'Language',
      'chooseLanguage': 'Choose Language',
      'budgetList': 'Budget List',
      'statistics': 'Statistics',
      'settings': 'Settings',
      'addExpense': 'Add Expense',
      'noExpenseDate': 'No expenses on this date.',
      'menu Utama': 'Main Menu',
      'manageBudget': 'Manage categories and allocations',
      'analytics': 'Expense analytics graphs',
      'aboutPrefs': 'App details and preferences',
      'generalSettings': 'General Settings',
      'selectLanguagePrompt': 'Please select your preferred language.',
      'save': 'Save',
      'cancel': 'Cancel',
      'close': 'Close',
      'expenseName': 'Expense Name',
      'expenseNameExample': 'Expense Name (e.g. Fried Rice)',
      'amount': 'Amount (Rp)',
      'addBudget': 'Add Budget',
      'editBudget': 'Edit Budget',
      'deleteBudget': 'Delete Budget',
      'deleteConfirm': 'Are you sure you want to delete this budget? All related expenses will also be deleted.',
      'deleteExpenseConfirm': 'Are you sure you want to delete this expense?\n\nFunds will be returned to the category budget.',
      'totalBalance': 'Total Balance This Month',
      'totalExpense': 'Total Expense This Month',
      'firstLaunchTitle': 'Welcome!',
      'remainingBudget': 'Remaining Budget',
      'total': 'Total: Rp',
      'spent': 'Spent: Rp',
      'expenseHistory': 'Expense History',
      'noExpenseCategory': 'No expenses\nin this category.',
      'editExpense': 'Edit Expense',
      'selectBudgetCategory': 'Select Budget Category',
      'deleteExpenseTitle': 'Delete Expense?',
      'delete': 'Delete',
      'budgetName': 'Budget Name',
      'allocatedFunds': 'Allocated Funds (Rp)',
      'noBudgetsYet': 'No budgets yet.\nPlease add a new budget.',
      'remaining': 'Remaining: Rp',
      'noBudgetAddedYet': 'No Budget Yet',
      'addBudgetFirst': 'Please add a budget first before recording an expense.',
      'recordExpense': 'Record Expense',
      'saveExpense': 'Save Expense',
      'appPreferences': 'App Preferences',
      'darkTheme': 'Dark Theme',
      'notifications': 'Notifications',
      'about': 'About',
      'appVersion': 'App Version',
      'termsConditions': 'Terms & Conditions',
      'privacyPolicy': 'Privacy Policy',
      'expenses': 'Expenses',
      'today': 'Today',
      'addBudgetNew': 'Add New Budget',
      'allocatedVsSpent': 'Allocated vs Spent per Category',
      'noBudgetData': 'No budget category data available.',
      'legend': 'Legend',
      'totalBudgetAllocation': 'Total Budget Allocation',
      'spentSafe': 'Spent (Safe)',
      'spentWarning': 'Spent (Nearing / Exceeding Limit)',
      'allExpenses': 'All Expenses',
      'totalRemainingBudget': 'Total Remaining Budget',
      'budgetDetails': 'Budget Details',
      'noBudgetRecorded': 'No budgets recorded yet.',
    }
  };
}
